<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0;net9.0</TargetFrameworks>
    <AssemblyName>RhubarbGeekNz.SQLiteConnection.Core.Alc</AssemblyName>
    <CertificateThumbprint>601A8B683F791E51F647D34AD102C38DA4DDB65F</CertificateThumbprint>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
    <Version>7.5.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <Version>7.4.5</Version>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <Version>7.2.23</Version>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.33" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
  </ItemGroup>

  <Target Name="Sign" AfterTargets="Compile" Condition=" '$(Configuration)' == 'Release' AND '$(OS)' == 'Windows_NT' ">
    <ItemGroup>
        <FileToSign Include="$(IntermediateOutputPath)$(TargetFileName)" />
    </ItemGroup>
    <Message Importance="high" Text="Signing assemblies: @(FileToSign)" />
    <SignFile
          SigningTarget="@(FileToSign)"
          CertificateThumbprint="$(CertificateThumbprint)"
          TimestampUrl="http://timestamp.digicert.com"
    />
  </Target>

</Project>
